server.port=8080

airflow.base-url=${AIRFLOW_BASE_URL:http://airflow-webserver:8080}
airflow.username=${AIRFLOW_USERNAME:admin}
airflow.password=${AIRFLOW_PASSWORD:admin}
airflow.dag-id=${AIRFLOW_DAG_ID:lumi_ingestion_dag}

lumi.postgres-dsn=${LUMI_POSTGRES_DSN}

lumi.split-threshold-bytes=${LUMI_SPLIT_THRESHOLD_BYTES:52428800}

lumi.docker-network=${LUMI_DOCKER_NETWORK:amex-lumi-case-study_default}

lumi.host-project-dir=${LUMI_HOST_PROJECT_DIR:}

lumi.pyspark-image=${LUMI_PYSPARK_IMAGE:amex-lumi-case-study-pyspark-splitter}
